---
title: "RLE_EPL_results"
format: html
---

```{r}
library(sf)
library(tidyverse)
library(readxl)
library(stringr)
```

```{r}
# Load the RLE and EPL results for Estuaries and then combine them and join to estuaries patial data
RLE <- read.csv("outputs/rle_est_metrics_per_type.csv")
#Fetch EPL results from REPO 
epl_est_git <- "https://raw.githubusercontent.com/SANBI-NBA/estuary-epl-analysis/main/outputs/epl_est_metrics_per_type.csv"
EPL <- read.csv(epl_est_git)

# select only cols required and then join
RLE <- RLE %>%
  select(full_ecosystem_type_name, tot_ext24, RLE18, trigger18, RLE24, trigger24)
EPL <- EPL %>%
  select(full_ecosystem_type_name, biogeographical_zone, EPL18_model, EPL24_model) %>% 
  rename(EPL18 = EPL18_model, EPL24 = EPL24_model)
  
est_results_type <- RLE %>%
  left_join(EPL, by = "full_ecosystem_type_name") %>%
  # combine RLE and EPL into a new col
  unite("RLE_EPL24", RLE24, EPL24, sep = "_", remove = FALSE) %>%
  # order the cols to show unluckies in right sequence
  mutate(RLE24 = factor(RLE24, levels = c("LC", "VU", "EN", "CR"), ordered = TRUE)) %>%
  mutate(EPL24 = factor(EPL24, levels = c("NP", "PP", "MP", "WP"), ordered = TRUE)) %>%
    mutate(RLE_EPL24 = factor(RLE_EPL24, levels = c("LC_WP", "LC_MP", "VU_WP", "VU_MP", "LC_PP",  "LC_NP",  "VU_PP", "VU_NP", "EN_WP", "EN_MP",  "CR_WP", "CR_MP","EN_PP" , "EN_NP","CR_PP", "CR_NP"), ordered = TRUE)) %>%
  relocate(biogeographical_zone, .after = full_ecosystem_type_name) %>%
  relocate(RLE_EPL24, .after = EPL24) %>%
mutate(extent = tot_ext24/1e6)

# MAKE simple output for coastal and overal integrated results and plots 
est_results_for_integration <- est_results_type %>%
  select(full_ecosystem_type_name, biogeographical_zone, extent, RLE24, EPL24, RLE_EPL24) %>%
  mutate(realm = "est") %>%
  rename(type = full_ecosystem_type_name, RLE = RLE24, EPL = EPL24, RLE_EPL = RLE_EPL24, zone = biogeographical_zone) %>%
   mutate(type = str_sub(type, 3)) %>%
   mutate(type = str_remove_all(type, " -"))
  


# write results
write.csv(est_results_type, file = "outputs/est_results_type.csv")
write.csv(est_results_for_integration, file = "outputs/est_results_for_integration.csv")

```

```{r}

```

```{r}
#Prepare output spatial data with combined RLE and EPL results
est_results_poly <- est_v3 %>%
  mutate(type = I_EcoType1) %>% # use this as it is the IEM name and integrated results name (full_ecosystem_type_name clean up of - and spaces) 
  left_join(est_results_for_integration, by = "type")

st_write(est_results_poly, 
         "C:/Users/skownoa/Dropbox/NBAwork/Estuaries/est_results_poly.gpkg", 
         delete_layer = TRUE)
st_write(st_transform(est_results_poly, 4326),
  "C:/Users/skownoa/Dropbox/NBAwork/Estuaries/est_results_poly_dd.gpkg",
  delete_layer = TRUE)


## Make a point shapefile output
# Fetch estuary point file from sharepoint
est_pnt_fp <- list.files(path = data_file_path, 
                           pattern = "^NBA2025_estuary_points_results\\.shp$",
                           recursive = TRUE,
                           full.names = TRUE)
# Join to results 
est_results_point <- st_read(est_pnt_fp) %>% 
                     left_join(est_t, by = c("OUTLET_IDw" = "outletID")) %>%
  select(OUTLET_IDw, type, efz_ha) %>%
  left_join(est_results_for_integration, by = "type") 


# Fetch boundaries
sa_fp <- list.files(path = data_file_path, 
                           pattern = "^SA_boundaries_v12\\.shp$",
                           recursive = TRUE,
                           full.names = TRUE)
sa <- st_read(
  sa_fp) %>% filter(OBJECTID != 3 &  OBJECTID != 12)

est_results_point <- st_transform(est_results_point, st_crs(sa))

st_write(est_results_point, 
         "C:/Users/skownoa/Dropbox/NBAwork/Estuaries/est_results_point_dd.gpkg", 
         delete_layer = TRUE)
```

```{r}

# try plot the results to check them 
map1 <- ggplot() +
  geom_sf(data = sa, fill = NA, color = "black", size = 0.5) +  # SA boundary
  geom_sf(
    data = est_results_point,
    aes(color = RLE, size = efz_ha),
    shape = 21, fill = NA, stroke = 1.5
  ) +
  scale_color_manual(
    values = c(
      "CR" = "red",
      "EN" = "orange",
      "VU" = "yellow",
      "LC" = "green"
    )
  ) +
  scale_size(range = c(1, 10)) +
  theme_void() +
  theme(
    legend.position = "right")
    
    #export the graph
ggsave(
  filename = "outputs/testmap.pdf", # File name
  plot = map1,                   # Plot object
  device = "pdf",  
  dpi = 300, 
  width = 12, height = 10, units = "cm"   # Dimensions
)
  
#export the graph
ggsave(
  filename = "outputs/testmap.jpeg", # File name
  plot = map1,                   # Plot object
  device = "jpeg",  
  dpi = 300, 
  width = 12, height = 10, units = "cm"   # Dimensions
)
  
```
